version: '3'

services:
  flask_app:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - mysql
    environment:
      - FLASK_APP=app
      - FLASK_RUN_HOST=0.0.0.0
      - FLASK_RUN_PORT=5000

  mysql:
    image: mysql:8.0.37
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: flaskdb
    volumes:
      - mysql-data:/var/lib/mysql

networks:
  my_network:
    driver: bridge

volumes:
  mysql-data:
